### ISSUE TITLE
Error 402 "Payment Required

### ISSUE THREAD

**Issue by itslevir** [getclaps/worker#1]
I've installed and payed for getclaps, I'm on the dashboard, and I have my website set on the getclaps dashboard. Yet I still get this:
![image](https://user-images.githubusercontent.com/72626657/112729236-6d2aa400-8ee8-11eb-87aa-0c40ea9f2b7f.png)
and
![image](https://user-images.githubusercontent.com/72626657/112729250-774ca280-8ee8-11eb-9e56-d0ce2ab89a52.png)
I tried using `<clap-button />` instead of `<clap-button></clap-button>`, I've tried adding the exact page instead of the domain, and nothing works. Could this be a problem with the dashboard or me?

**Comment by qwtel** [comment]
This was a bug in getclaps/button@102e043, which now fixed (version 1.0.0-alpha.18 and upwards)

Thanks for reporting this.

PS: `<clap-button></clap-button>` is the correct way to use it.
